### ISSUE TITLE
500 error when pip installing packages and using object storage

### ISSUE THREAD

**Issue by daviddavis** [pulp/pulp_python#572]
**Version**
pulpcore 3.21.0
pulp_python 3.7.3

**Describe the bug**
I'm not totally sure I understand what's going on. But it seems like [the pulp_python code sets up a remote to fetch the index.html from object storage](https://github.com/pulp/pulp_python/blob/d16f52934d6daee1603059c78131993da98680a0/pulp_python/app/models.py#L109-L114). Then we hit aiohttp.client_exceptions.ClientConnectorCertificateError. It looks like in doing this aiohttp isn't using the trusted CA for some reason.

It should be noted that the environment is set up properly as I can fetch other content from the distribution such as the wheel files without any ClientConnectorCertificateErrors. These files are stored in Azure storage but obviously fetched via django-storages module. Not sure what the difference is that's causing the ClientConnectorCertificateErrors.

**To Reproduce**
Set up your pulp instance to use Azure Storage and then upload a package to a repo, distribute it, and then try to install it. I think the workflow from the docs should suffice.

**Expected behavior**
The package installs.

**Comment by daviddavis** [comment]
Full stacktrace:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/lib/python3.9/site-packages/pulpcore/content/authentication.py", line 41, in authenticate
    return await handler(request)
  File "/usr/lib/python3.9/site-packages/pulpcore/content/handler.py", line 237, in stream_content
    return await self._match_and_stream(path, request)
  File "/usr/lib/python3.9/site-packages/pulpcore/content/handler.py", line 651, in _match_and_stream
    return await self._stream_remote_artifact(
  File "/usr/lib/python3.9/site-packages/pulpcore/download/http.py", line 273, in run
    return await download_wrapper()
  File "/usr/lib/python3.9/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pulpcore/download/http.py", line 258, in download_wrapper
    return await self._run(extra_data=extra_data)
  File "/usr/lib/python3.9/site-packages/pulpcore/download/http.py", line 291, in _run
    async with self.session.get(
  File "/usr/lib/python3.9/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/usr/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/lib/python3.9/site-packages/aiohttp/connector.py", line 982, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host pulpblobstorage.blob.core.windows.net:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1129)')]
::ffff:10.169.23.80 [19/Oct/2022:20:00:20 +0000] "GET /pypi/simple/ HTTP/1.0" 500 315 "http://pulp.internal/pypi/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
```

**Comment by daviddavis** [comment]
A change that would unblock us (although not solve this issue) would be to disable this code path when REDIRECT_TO_OBJECT_STORAGE is false as this functionality doesn't make sense [since pulp is streaming the files from object storage to the user](https://github.com/pulp/pulpcore/blob/35e5b669044aa6f4cdca677ba89139adc2461c55/pulpcore/content/handler.py#L820-L821) instead of redirecting requests. I'm happy to open up a PR with this change.

```diff
diff --git a/pulp_python/app/models.py b/pulp_python/app/models.py
index 7574aac..073e4d4 100644
--- a/pulp_python/app/models.py
+++ b/pulp_python/app/models.py
@@ -75,7 +75,10 @@ class PythonDistribution(Distribution):
         elif len(path.parts) and path.parts[0] == "simple":
             # Temporary fix for PublishedMetadata not being properly served from remote storage
             # https://github.com/pulp/pulp_python/issues/413
-            if settings.DEFAULT_FILE_STORAGE != "pulpcore.app.models.storage.FileSystem":
+            if (
+                settings.DEFAULT_FILE_STORAGE != "pulpcore.app.models.storage.FileSystem"
+                and settings.REDIRECT_TO_OBJECT_STORAGE
+            ):
                 try:
                     publication = self.publication or Publication.objects.filter(
                         repository_version=self.repository.latest_version()).latest("pulp_created")
```

**Comment by daviddavis** [comment]
FYI, this works great. Thanks!
